/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Com.company.fashiondesktop.GUI;


/**
 *
 * @author levan
 */
public class DANGNHAP extends javax.swing.JFrame {

    /**
     * Creates new form DANGNHAP
     */
    private boolean isPasswordVisible = false;
    
    public DANGNHAP() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("QUẢN LÍ BÁN HÀNG");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        TENDANGNHAP = new javax.swing.JTextField();
        NHAPMATKHAU = new javax.swing.JPasswordField();
        GHINHO = new javax.swing.JCheckBox();
        HIENMATKHAU = new javax.swing.JButton();
        ANMATKHAU = new javax.swing.JButton();
        DANGNHAP = new javax.swing.JButton();
        DANGKY = new javax.swing.JLabel();
        QUENMATKHAU = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 440, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 440, 10));

        jSeparator3.setAlignmentY(1.0F);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 90, 20));

        TENDANGNHAP.setBackground(new java.awt.Color(0, 0, 0));
        TENDANGNHAP.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TENDANGNHAP.setForeground(new java.awt.Color(255, 255, 255));
        TENDANGNHAP.setText("abcxyz123@");
        TENDANGNHAP.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        TENDANGNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TENDANGNHAPActionPerformed(evt);
            }
        });
        jPanel1.add(TENDANGNHAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 370, 40));

        NHAPMATKHAU.setBackground(new java.awt.Color(0, 0, 0));
        NHAPMATKHAU.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        NHAPMATKHAU.setForeground(new java.awt.Color(255, 255, 255));
        NHAPMATKHAU.setText("nhapmatkhau");
        NHAPMATKHAU.setToolTipText("Nhập mật khẩu của bạn");
        NHAPMATKHAU.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NHAPMATKHAU.setEchoChar('*');
        NHAPMATKHAU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NHAPMATKHAUFocusGained(evt);
            }
        });
        NHAPMATKHAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NHAPMATKHAUActionPerformed(evt);
            }
        });
        jPanel1.add(NHAPMATKHAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 370, 40));

        GHINHO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        GHINHO.setForeground(new java.awt.Color(255, 255, 255));
        GHINHO.setText("Ghi nhớ");
        jPanel1.add(GHINHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, -1));

        HIENMATKHAU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hien.png"))); // NOI18N
        HIENMATKHAU.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        HIENMATKHAU.setContentAreaFilled(false);
        HIENMATKHAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HIENMATKHAUMouseClicked(evt);
            }
        });
        HIENMATKHAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIENMATKHAUActionPerformed(evt);
            }
        });
        jPanel1.add(HIENMATKHAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 40, 30));

        ANMATKHAU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/eye.png"))); // NOI18N
        ANMATKHAU.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ANMATKHAU.setContentAreaFilled(false);
        ANMATKHAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ANMATKHAUMouseClicked(evt);
            }
        });
        ANMATKHAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANMATKHAUActionPerformed(evt);
            }
        });
        jPanel1.add(ANMATKHAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 40, 30));

        DANGNHAP.setBackground(new java.awt.Color(255, 51, 102));
        DANGNHAP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        DANGNHAP.setForeground(new java.awt.Color(255, 255, 255));
        DANGNHAP.setText("ĐĂNG NHẬP");
        DANGNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DANGNHAPActionPerformed(evt);
            }
        });
        jPanel1.add(DANGNHAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 440, 50));

        DANGKY.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        DANGKY.setForeground(new java.awt.Color(255, 255, 255));
        DANGKY.setText("Đăng ký");
        DANGKY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DANGKYMouseClicked(evt);
            }
        });
        jPanel1.add(DANGKY, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 100, -1));

        QUENMATKHAU.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        QUENMATKHAU.setForeground(new java.awt.Color(255, 255, 255));
        QUENMATKHAU.setText("Quên mật khẩu?");
        jPanel1.add(QUENMATKHAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/lock.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 30, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 40, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐĂNG NHẬP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 310, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bgr.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DANGNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DANGNHAPActionPerformed

    }//GEN-LAST:event_DANGNHAPActionPerformed

    private void DANGKYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DANGKYMouseClicked
        GuiSign_in si = new GuiSign_in();
        si.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DANGKYMouseClicked

    private void TENDANGNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TENDANGNHAPActionPerformed
        NHAPMATKHAU.requestFocus();
    }//GEN-LAST:event_TENDANGNHAPActionPerformed

    private void HIENMATKHAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIENMATKHAUActionPerformed

    }//GEN-LAST:event_HIENMATKHAUActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TENDANGNHAP.selectAll();
        TENDANGNHAP.requestFocus();
        
        // Thiết lập trạng thái ban đầu
//        NHAPMATKHAU.setEchoChar('*');      // Đảm bảo mật khẩu bị che
        HIENMATKHAU.setVisible(true);  // Hiển thị label HIENMATKHAU
        ANMATKHAU.setVisible(false);   // Ẩn label ANMATKHAU
    }//GEN-LAST:event_formWindowOpened

    private void NHAPMATKHAUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NHAPMATKHAUFocusGained
        NHAPMATKHAU.selectAll();
    }//GEN-LAST:event_NHAPMATKHAUFocusGained

    private void NHAPMATKHAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NHAPMATKHAUActionPerformed
        DANGNHAP.doClick();
    }//GEN-LAST:event_NHAPMATKHAUActionPerformed

    private void ANMATKHAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANMATKHAUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ANMATKHAUActionPerformed

    private void HIENMATKHAUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HIENMATKHAUMouseClicked
        NHAPMATKHAU.setEchoChar((char) 0); // Hiển thị mật khẩu (không che)
        HIENMATKHAU.setVisible(false); // Ẩn label HIENMATKHAU
        ANMATKHAU.setVisible(true);    // Hiện label ANMATKHAU
        NHAPMATKHAU.requestFocus();
    }//GEN-LAST:event_HIENMATKHAUMouseClicked

    private void ANMATKHAUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ANMATKHAUMouseClicked
        NHAPMATKHAU.setEchoChar('*');      // Che mật khẩu bằng dấu *
        ANMATKHAU.setVisible(false);   // Ẩn label ANMATKHAU
        HIENMATKHAU.setVisible(true);  // Hiện label HIENMATKHAU
        NHAPMATKHAU.requestFocus();
    }//GEN-LAST:event_ANMATKHAUMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DANGNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DANGNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DANGNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DANGNHAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DANGNHAP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANMATKHAU;
    private javax.swing.JLabel DANGKY;
    private javax.swing.JButton DANGNHAP;
    private javax.swing.JCheckBox GHINHO;
    private javax.swing.JButton HIENMATKHAU;
    private javax.swing.JPasswordField NHAPMATKHAU;
    private javax.swing.JLabel QUENMATKHAU;
    private javax.swing.JTextField TENDANGNHAP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
